# Setup nginx
- name: install nginx main file
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
            owner=root group=root mode=644
  notify: restart nginx
  tags:
    - nginx
    - static

- name: ensuring default nginx site is not there
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags: nginx

- name: ensuring that the upload dir is there
  file: path=/srv/uploads/audio state=directory
  tags: nginx

- name: install nginx site config file
  template: src=app.conf dest=/etc/nginx/sites-available/oldspeak.conf
            owner=root group=root mode=644
  notify: restart nginx
  tags: nginx

- name: enable nginx site config file
  file: src=/etc/nginx/sites-available/oldspeak.conf dest=/etc/nginx/sites-enabled/oldspeak.conf owner=www-data group=www-data state=link
  notify: restart nginx
  tags:
    - nginx
    - static
