---
- hosts:
    - oldspeak

  user: root
  vars:
    root_domain_tls_cert_path:  /etc/ssl/certs/oldspeak.cert
    root_domain_tls_key_path:  /etc/ssl/certs/oldspeak.key
    hidden_service_active: yes
    gitea_version: "1.0.1"
    libgit2_version: "0.25.0"
    libgpgme_version: "1.8.0"
    local_repository_root_path: "{{ playbook_dir }}/.."
    system_max_file_descriptors: 32768
    ulimit_config:
      - {domain: '*', type: soft, item: nofile, value: 32768}
      - {domain: '*', type: hard, item: nofile, value: 32768}
      - {domain: 'root', type: soft, item: nofile, value: 32768}
      - {domain: 'root', type: hard, item: nofile, value: 32768}

    digital_ocean_volumes:
      - name: "volume-nyc1-02"
        mountpoints:
          - /mnt/volume

  vars_files:
    - "hardening-config.yml"
    - "oldspeak-vault.yml"

  roles:
    # # digitalocean turns-on the droplet(s),
    # # so it should be executed first:
    # - digitalocean

    # # system integrity, can be commented out in favor of speedup application deployment
    # - system-updates
    # - system-hardening
    # - enable-standard-cronjobs
    # - ulimit

    # python application
    # - mysql-db
    # - prosody
    # - ssl
    - web
    - onion


# TODO:
# -----
#
# - https://github.com/jacoelho/ansible.ipsec
# - https://en.wikipedia.org/wiki/IPsec
# - https://github.com/neilalexander/sigmavpn/
