---
- hosts:
    - oldspeak

  user: root
  vars:
    gitea_version: "1.0.1"
    libgit2_version: "0.25.0"
    libgpgme_version: "1.8.0"
    local_repository_root_path: "{{ playbook_dir }}/.."
    system_max_file_descriptors: 32768
    ulimit_config:
      - {domain: '*', type: soft, item: nofile, value: 32768}
      - {domain: '*', type: hard, item: nofile, value: 32768}
      - {domain: 'root', type: soft, item: nofile, value: 32768}
      - {domain: 'root', type: hard, item: nofile, value: 32768}

    digital_ocean_volumes:
      - volume-nyc1-02

  vars_files:
    - "hardening-config.yml"
    - "oldspeak-vault.yml"

  roles:
    # - system-updates
    # - system-hardening
    # - enable-standard-cronjobs
    # - ulimit
    # - docker
    - onion
    - gitea
    - oldspeak


# TODO:
# -----
#
# - https://github.com/jacoelho/ansible.ipsec
# - https://en.wikipedia.org/wiki/IPsec
# - https://github.com/neilalexander/sigmavpn/
