- name: "installing base dependencies"
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - ntp
    - nginx
    - upstart
    - telnet
    - git
    - coreutils
    - tree
    - vim
    - curl
    - cmake
    - git-svn
    - ca-certificates
    - build-essential
    - python
    - htop
    - subversion
    - wget
    - pkg-config
    - redis-server
    - redis-tools
    - virtualenvwrapper

- name: "create oldspeak application group"
  group:
    name: oldspeak
    state: present

- name: "create main service group"
  group:
    name: oldspeak-services
    state: present

- name: "creating oldspeak application user"
  user: >
    name=oldspeak
    shell=/usr/sbin/nologin
    group=oldspeak
    groups=oldspeak,oldspeak-services
    home=/srv/run

- name: "add www-data to the services group"
  user: >
    name=www-data
    groups=www-data,oldspeak-services
    home=/srv/run

- name: "creating folders"
  file: path={{ item }} state=directory recurse=yes owner=oldspeak group=oldspeak mode=0775
  with_items:
    - /srv/ssh
    - /srv/log
    - /srv/log/nginx
    - /srv/mail
    - /srv/uploads
    - /srv/pkgs
    - /srv/private-data
    - /srv/public-data
    - /srv/run
    - /srv/external
    - /srv/open-source

- name: "installing python dependencies"
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - python-pip
    - python-dev
    - python-virtualenv
    - libffi-dev
    - libssl-dev
    - libgcrypt11-dev
    - libudev-dev
    - libev-dev
    - libnss3
    - libgpg-error-dev
    - libgpgme11-dev

- name: download libgit2
  shell: wget https://github.com/libgit2/libgit2/archive/v{{ libgit2_version }}.tar.gz -O /srv/pkgs/libgit2-v{{ libgit2_version }}.tar.gz
  args:
    chdir: "/srv/pkgs"

- name: extract libgit2
  shell: tar xzf /srv/pkgs/libgit2-v{{ libgit2_version }}.tar.gz -C /srv/pkgs/
  args:
    chdir: "/srv/pkgs"

- name: cmake [libgit2]
  shell: cmake .
  args:
    chdir: "/srv/pkgs/libgit2-{{ libgit2_version }}"

- name: make [libgit2]
  shell: make
  args:
    chdir: "/srv/pkgs/libgit2-{{ libgit2_version }}"

- name: make install [libgit2]
  shell: make install
  args:
    chdir: "/srv/pkgs/libgit2-{{ libgit2_version }}"

- name: rsync-copying local code to server
  synchronize:
    src: ../../../../
    dest: /srv/src
    links: yes
    delete: yes

# Python dependencies

- name: install latest setuptools
  pip: name=setuptools state=latest
       virtualenv="{{ venv_path }}"

- name: install latest pip
  pip: name=pip state=latest
       virtualenv="{{ venv_path }}"

- name: install gunicorn
  pip: name=gunicorn state=latest
       virtualenv="{{ venv_path }}"

- name: install requirements
  pip: requirements="/srv/src/requirements.txt"
       virtualenv="{{ venv_path }}"

- name: "!! uninstall oldspeak !!"
  shell: "/srv/venv/bin/pip uninstall -y oldspeak"
  ignore_errors: yes

- name: "!! install oldspeak !!"
  shell: "/srv/venv/bin/python setup.py install"
  args:
    chdir: "/srv/src"
  notify:
    - restart python-app
