- name: "installing base dependencies"
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - ntp
    - nginx
    - upstart
    - telnet
    - git
    - coreutils
    - tree
    - vim
    - curl
    - cmake
    - git-svn
    - ca-certificates
    - build-essential
    - python
    - htop
    - subversion
    - wget
    - pkg-config
    - redis-server
    - redis-tools
    - virtualenvwrapper

- name: "create oldspeak application group"
  group:
    name: oldspeak
    state: present

- name: "create main service group"
  group:
    name: oldspeak-services
    state: present

- name: "creating oldspeak application user"
  user: >
    name=oldspeak
    shell=/usr/sbin/nologin
    group=oldspeak
    groups=oldspeak,oldspeak-services
    home=/srv/run

- name: "add www-data to the services group"
  user: >
    name=www-data
    groups=www-data,oldspeak-services
    home=/srv/run

- name: "creating folders"
  file: path={{ item }} state=directory recurse=yes owner=oldspeak group=oldspeak mode=0775
  with_items:
    - /srv/ssh
    - /srv/log
    - /srv/log/nginx
    - /srv/mail
    - /srv/uploads
    - /srv/pkgs
    - /srv/private-data
    - /srv/public-data
    - /srv/run
    - /srv/external
    - /srv/open-source
