- name: download libgpgme
  shell: wget https://github.com/libgpgme/libgpgme/archive/v{{ libgpgme_version }}.tar.gz -O /srv/pkgs/libgpgme-v{{ libgpgme_version }}.tar.gz
  args:
    chdir: "/srv/pkgs"

- name: extract libgpgme
  shell: tar xzf /srv/pkgs/libgpgme-v{{ libgpgme_version }}.tar.gz -C /srv/pkgs/
  args:
    chdir: "/srv/pkgs"

- name: cmake [libgpgme]
  shell: cmake .
  args:
    chdir: "/srv/pkgs/libgpgme-{{ libgpgme_version }}"

- name: make [libgpgme]
  shell: make
  args:
    chdir: "/srv/pkgs/libgpgme-{{ libgpgme_version }}"

- name: make install [libgpgme]
  shell: make install
  args:
    chdir: "/srv/pkgs/libgpgme-{{ libgpgme_version }}"
