- name: download libgit2
  shell: wget https://github.com/libgit2/libgit2/archive/v{{ libgit2_version }}.tar.gz -O /srv/pkgs/libgit2-v{{ libgit2_version }}.tar.gz
  args:
    chdir: "/srv/pkgs"

- name: extract libgit2
  shell: tar xzf /srv/pkgs/libgit2-v{{ libgit2_version }}.tar.gz -C /srv/pkgs/
  args:
    chdir: "/srv/pkgs"

- name: cmake [libgit2]
  shell: cmake .
  args:
    chdir: "/srv/pkgs/libgit2-{{ libgit2_version }}"

- name: make [libgit2]
  shell: make
  args:
    chdir: "/srv/pkgs/libgit2-{{ libgit2_version }}"

- name: make install [libgit2]
  shell: make install
  args:
    chdir: "/srv/pkgs/libgit2-{{ libgit2_version }}"
