- name: "create oldspeak application group"
  group:
    name: oldspeak
    state: present

- name: "create main service group"
  group:
    name: oldspeak-services
    state: present

- name: "creating oldspeak application user"
  user: >
    name=oldspeak
    shell=/usr/sbin/nologin
    group=oldspeak
    groups=oldspeak,oldspeak-services
    home=/srv/run

- name: "add www-data to the services group"
  user: >
    name=www-data
    groups=www-data,oldspeak-services
    home=/srv/run

- name: "creating folders"
  file: path={{ item }} state=directory recurse=yes owner=oldspeak group=oldspeak mode=0775
  with_items:
    - /srv/ssh
    - /srv/log
    - /srv/log/nginx
    - /srv/mail
    - /srv/uploads
    - /srv/pkgs
    - /srv/private-data
    - /srv/public-data
    - /srv/run
    - /srv/external
    - /srv/open-source

- name: "ensure main permissions"
  shell: chown -R oldspeak:oldspeak-services "{{ item }}"
  with_items:
    - /srv
    - /srv/mail
    - /srv/open-source
    - /srv/private-data
    - /srv/public-data
    - /srv/src
    - /srv/ssh
    - /srv/uploads

- name: "ensure service-wide group permissions"
  shell: chown -R oldspeak:oldspeak-services "{{ item }}"
  with_items:
    - /srv/log
    - /srv/open-source
    - /srv/public-data
    - /srv/src
    - /srv/src/static
