- name: "installing python dependencies"
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - python-pip
    - python-dev
    - python-virtualenv
    - libffi-dev
    - libssl-dev
    - libgcrypt11-dev
    - libudev-dev
    - libev-dev
    - libnss3
    - libgpg-error-dev

- name: sync local repo with server 0rbitAeolian/OldSpeak
  synchronize: src="{{ local_repository_root_path }}" dest="/srv/src" recursive=yes

# Python dependencies

- name: install latest setuptools
  pip: name=setuptools state=latest
       virtualenv="{{ venv_path }}"

- name: install latest pip
  pip: name=pip state=latest
       virtualenv="{{ venv_path }}"

- name: install gunicorn
  pip: name=gunicorn state=latest
       virtualenv="{{ venv_path }}"

- name: install requirements
  pip: requirements="/srv/src/requirements.txt"
       virtualenv="{{ venv_path }}"

- name: "!! uninstall oldspeak !!"
  shell: "/srv/venv/bin/pip uninstall -y oldspeak"
  ignore_errors: yes

- name: "!! install oldspeak !!"
  shell: "/srv/venv/bin/python setup.py install"
  args:
    chdir: "/srv/src"
  environment:
    CPLUS_INCLUDE_PATH: "/srv/pkgs/gpgme-{{ libgpgme_version }}:/srv/pkgs/libgit2-{{ libgit2_version }}"
    C_INCLUDE_PATH: "/srv/pkgs/gpgme-{{ libgpgme_version }}:/srv/pkgs/libgit2-{{ libgit2_version }}"
    LD_LIBRARY_PATH: "/srv/pkgs/gpgme-{{ libgpgme_version }}:/srv/pkgs/libgit2-{{ libgit2_version }}"

  notify:
    - restart python-app
